name: CI
env:
  BUILD_CONFIGURATION: Release
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install gcc make g++ libtool cmake dbus libdbus-1-dev
    - name: Build
      run: |
        cpus=$(grep -c processor /proc/cpuinfo)
        mkdir build
        cd build || exit
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE || exit
        make -j "${cpus}"
